tasks:
  - name: Pip Install
    command: pip install -r requirements.txt

vscode:
  extensions:
    - dracula-theme.theme-dracula
    - ms-python.python
    - usernamehw.errorlens
    - wayou.vscode-todo-highlight
    - gruntfuggly.todo-tree
    - whitphx.vscode-stlite
    - yzhang.markdown-all-in-one
    - trunk.io
