version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: mock -h 0.0.0.0 /tmp/santas_sleigh.oas.0.0.yaml # --dynamic
    volumes:
      - ../contract/santas_sleigh.oas.0.0.yaml:/tmp/santas_sleigh.oas.0.0.yaml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - 8080:4010